name: Deploy Doc Website
on:
  push:
    branches:
      - develop

jobs:
  master-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Npm Install
        run: npm install
        
      - name: Build Website
        run: npm run website-prod:build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          token: ${{ secrets.WEB_TOKEN }}
          branch: pages
          folder: web
          repository-name: Every-UI/every-ui.github.io
          git-config-name: EveryUIBot
          git-config-email: everyui2021@gmail.com
          commit-message: website deploy
