name: Deploy Doc Website
on:
  push:
    branches:
      - develop

jobs:
  master-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup node
        uses: actions/setup-node@v1

      - name: Build Website
        run: website-prod:build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: website-dist
          GIT_CONFIG_NAME: EveryUIBot
          GIT_CONFIG_EMAIL: everyui2021@gmail.com
          COMMIT_MESSAGE: website deploy
